### ISSUE TITLE
Update Maker's link 

### ISSUE THREAD

**Issue by dpazdan** [MetaMask/dapps#34] opened 2020-05-01 01:16 UTC
Update from the old CDP site link to their new Oasis site:
https://oasis.app/

![image](https://user-images.githubusercontent.com/16330048/80773388-5f756e80-8b1f-11ea-8604-d3a2f407441c.png)

**Comment by jennypollack** [comment] 2020-05-01 08:56
Duplicate of #32

**Closed by jennypollack** 2020-05-01 08:56 UTC
